const PORT = process.env.PORT || 5000;
const MONGO_CONNECTION_STRING = process.env.MONGO_CONNECTION_STRING;
const AWS_ACCESS_KEY_ID = process.env.AWS_ACCESS_KEY_ID;
const AWS_SECRET_ACCESS_KEY = process.env.AWS_SECRET_ACCESS_KEY;
const AWS_BUCKET_NAME = process.env.AWS_BUCKET_NAME;
const JWT_SECRET = process.env.JWT_SECRET;
const FRONTEND_URL = process.env.FRONTEND_URL;
const AWS_REGION = process.env.AWS_REGION;
const AWS_SES_EMAIL_FROM = process.env.AWS_SES_EMAIL_FROM;
const FRONTEND_ADMIN_URL = process.env.FRONTEND_ADMIN_URL;
const TWILIO_ACCOUNT_SID = process.env.TWILIO_ACCOUNT_SID;
const TWILIO_AUTH_TOKEN = process.env.TWILIO_AUTH_TOKEN;
const TWILIO_PHONE_NUMBER = process.env.TWILIO_PHONE_NUMBER;
const SENDGRID_API_KEY = process.env.SENDGRID_API_KEY;
const SENDGRID_EMAIL_FROM = process.env.SENDGRID_EMAIL_FROM;

module.exports = {
  PORT,
  AWS_ACCESS_KEY_ID,
  AWS_SECRET_ACCESS_KEY,
  AWS_BUCKET_NAME,
  JWT_SECRET,
  FRONTEND_URL,
  AWS_REGION,
  AWS_SES_EMAIL_FROM,
  FRONTEND_ADMIN_URL,
  MONGO_CONNECTION_STRING,
  TWILIO_ACCOUNT_SID,
  TWILIO_AUTH_TOKEN,
  TWILIO_PHONE_NUMBER,
  JWT_SECRET,
  FRONTEND_URL,
  SENDGRID_API_KEY,
  SENDGRID_EMAIL_FROM,
};
